# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84e831648a3624fecc596505aaa9cb07d86ab85503ef452da7c8187a03b203371ad4e76d40dde111aa3ead8a9a93fa51d598ca35fe8344afaebbd819ead9c4c3

test:
  secret_key_base: 64137eb23811cbf70ac7dccf0d609c3503a0435d1be3a2d8563b5826a827a363b07cbb8478785fd99737b24f316a8fc9bf1b69558fd9f500ff14dd58570ea1ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
